name: sfh
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  dart_mappable: ^4.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_onboarding_slider: ^1.0.11
  intl: ^0.18.1
  nb_utils: ^6.1.3
  pinput: ^4.0.0
  supabase_flutter: ^2.3.4

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true
  generate: true
